### ISSUE TITLE
Periodic Dropouts Online History

### ISSUE THREAD

**Issue by Data-Monkey** [Data-Monkey/Pi.Alert#6]
I'm getting these periodic dropouts in the online history table:

![image](https://github.com/Data-Monkey/Pi.Alert/assets/7224371/fe5eb549-949d-426c-a620-e664aa74679c)

![image](https://github.com/Data-Monkey/Pi.Alert/assets/7224371/7ad6dd2b-0e20-417d-a447-d0737fac4568)

This might be related to DB locks, but I'm only guessing...

The data should be saved to the DB in this method AFAIK:

https://github.com/Data-Monkey/Pi.Alert/blob/b814a856d0ff4b6c148c844b205528e4246ac3c9/pialert/database.py#LL417C20-L417C20

**Comment by jokob-sk** [comment]
`db.read` vs `db.read_one` issue?

**Comment by Data-Monkey** [comment]
I haven't looked into what this actually does in detail.
Do you have any error messages?
Maybe I am no longer running all the steps in the correct order. If the history runs before a scan runs it might be like that.
Are all the devices that are offline from the same scan-type?

**Comment by jokob-sk** [comment]
Could it be that these calls return `0`?

https://github.com/Data-Monkey/Pi.Alert/blob/b814a856d0ff4b6c148c844b205528e4246ac3c9/pialert/database.py#L425

It's also weird that this keeps happening in-between scans, but the correct values are entered after an actual scan

**Comment by jokob-sk** [comment]
Ah, maybe cycle is not initialized? as its a global ?

https://github.com/Data-Monkey/Pi.Alert/blob/b814a856d0ff4b6c148c844b205528e4246ac3c9/pialert/database.py#LL428C84-L428C89

**Comment by Data-Monkey** [comment]
networkscan passes in the global cycle:

[insertOnlineHistory(db,conf.cycle)](https://github.com/Data-Monkey/Pi.Alert/blob/b814a856d0ff4b6c148c844b205528e4246ac3c9/pialert/networkscan.py#LL120C39-L120C39)

**Comment by jokob-sk** [comment]
Last time this SQL query was changed it was targeting a different DB table... not sure even if cycle is required (maybe removing the where statement would fix this)? Still investigating:

https://github.com/jokob-sk/Pi.Alert/commit/51027f6b305057c40595cf39af72d7286c10e856

**Comment by jokob-sk** [comment]
Just checked the DB - I think we can safely remove the where clause:

![image](https://github.com/Data-Monkey/Pi.Alert/assets/96159884/41b6822d-129c-4b2a-b20b-ce4483e42b4e)

**Comment by jokob-sk** [comment]
Figured it out I think - the method is called even if there is no data in the CurrentScan table. The method is called more often than before (even if a scan is not being processed) so it returns 0. Previously the method was only executed if data in the CurrentScan  table were present.

**Comment by Data-Monkey** [comment]
Great Find!
So it must only run after a scan was actually executed. 
If all the scans run and found nothing it would be correct to set everything to offline. 

Yes, I remember there was a problem that I don't know how to return anything from the scan_network() method into the main loop as it is multiprocessing again. Maybe I need to call one from the other. I think it was all 1 big script before.

**Comment by Data-Monkey** [comment]
Is it ever possible to have no devices in CurrentScan? 
The actual host of the docker should always be there, no?
Maybe we can just say if CurrentScan is empty skip the InsertOnlineHistory?

**Comment by jokob-sk** [comment]
Yeeah, I think that's acceptable - it's only for stats - no other functionality is dependent on it

**Comment by Data-Monkey** [comment]
I added the check to run only if there are records in the CurrentScan table. Also hopefully fixed the read_one() that was not actually working when there was only 1 record in the result!

**Comment by jokob-sk** [comment]
great! seems fixed: 

![image](https://github.com/Data-Monkey/Pi.Alert/assets/96159884/3a33e942-ef1c-4935-80f9-f731ab0c9c74)
