### ISSUE TITLE
Plugins not being executed

### ISSUE THREAD

**Issue by jokob-sk** [Data-Monkey/Pi.Alert#7]
in `plugin.py`

```python

def run_plugin_scripts(db, runType, plugins = conf.plugins):

    # Header
    updateState(db,"Run: Plugins")

    mylog('debug', ['[Plugins] Check if any plugins need to be executed on run type: ', runType])

    for plugin in plugins:

        shouldRun = False

```

it should probably be 

```python

 for plugin in conf.plugins:

```

`len(plugins)` results in  `0`
`len(conf.plugins)` results in `7`

**Comment by Data-Monkey** [comment]
this should already make it conf.plugins unless the wrong parameter is passed in:
```python
def run_plugin_scripts(db, runType, plugins = conf.plugins):
```
but none of the calls pass in the plugin parameter. So I removed it for now.
(I don't like these global variables)

**Comment by jokob-sk** [comment]
> (I don't like these global variables)

Yep, should have cleaned this up a long time ago, didn't have the energy for it though... :/

**Comment by Data-Monkey** [comment]
plugins running. 
Only tested Undiscoverables so far, but working.

**Comment by jokob-sk** [comment]
The execution of plugins is verified > Closing
